# Generated by Django 3.0.3 on 2020-04-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indeed_vacatures', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='expired',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='alles',
            field=models.CharField(default='', max_length=50000),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='datum',
            field=models.DateTimeField(),
        ),
    ]
