# Generated by Django 3.0.3 on 2020-04-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titel', models.CharField(default='', max_length=350)),
                ('bedrijf', models.CharField(default='', max_length=350)),
                ('plaats', models.CharField(default='', max_length=350)),
                ('datum', models.CharField(default='', max_length=350)),
                ('link', models.CharField(default='', max_length=350)),
                ('expired', models.CharField(default='', max_length=350)),
            ],
        ),
    ]
