# Generated by Django 3.0.6 on 2020-05-11 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indeed_vacatures', '0002_auto_20200430_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='datum',
        ),
    ]
