# Generated by Django 3.0.6 on 2020-05-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indeed_vacatures', '0003_remove_jobpost_datum'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='zoekterm',
            field=models.CharField(default='', max_length=350),
        ),
    ]
