# Generated by Django 3.0.6 on 2020-05-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indeed_vacatures', '0004_jobpost_zoekterm'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='site',
            field=models.CharField(default='', max_length=350),
        ),
    ]
